### ISSUE TITLE
pLoop doesn't detect Halloween and automatically run garbo nobarf, then freecandy

### ISSUE THREAD

**Issue by Ignose** [Prusias-kol/pLooper#1]
Solution: Create a case statement, or introduce the following code in garboUsage directly after useLodestone()

if (holiday() == "Halloween"){
	if (yachtzeeAccess())
        	cli_execute("garbo candydish yachtzeechain nobarf" + x);
   	else
        	cli_execute("garbo candydish nobarf" + x);
    	cli_execute("freecandy");
    }

**Comment by Prusias-kol** [comment]
done
