### ISSUE TITLE
Leg 2 End of Day

### ISSUE THREAD

**Issue by capncastom** [Prusias-kol/pLooper#10]
First, thanks again for ploop and ptrack! Lovely scripts that I enjoy immensely.

End of day, leg 2: 
I find that when nightcapping is not prohibited due to mallbuy limits and consumables on hand (that is to say, when ploop runs to completion,) I more often than not am left over the adv/pvp caps both.

Well, to be honest, not overcapping via the script, but when I make a few optimal adjustments, I am overcapped.

When left to my own devices (script halt pre-nightcap because mallbuy limit for example,) I run all available pvp fites before nightcap to make sure I waste none. I don't know if there is a reason I'm unaware of to bank all until the next day, beside maybe increasing likelihood of unique target minis?  If that were the case, maybe burning down a few (intelligently or no?) would be optimal?

As for the Adv cap and optimizing:
I always rollover with the ToT in unicorn pjs.  I notice that ploop doesnt care and just throws solid shifting time weirdness on the stooper.
Ploop also doesnt cast Aug. 13 for the offhand remarkable buff.
(maybe it would if I owned a lefty? I dont. But either way, it always finishes with the August Scepter cast to spare, and I think thats the one to go for?)

Anyway, just some thoughts. Thanks for reading if you did :)

**Comment by capncastom** [comment]
oh, and I noticed just recently that the EoD nightcapping has taken to using spice melanges and over capping rollover advs by like 60ish.

Maybe I inadvertently tweaked my VoA somewhere, but regardless maybe a rollcap safeguard would be nice.


_EDIT:
I think `prusias_ploop_preHalloweenMPA` | `9999` set a new VoA for the most recent halloween, but did not change it back to my original VoA following.
I suppose having the value set that high gave the script the greenlight for spice melange usage._

**Comment by Prusias-kol** [comment]
Fixed halloween issue. Previously if ploop broke during halloween, could leave ur VOA hanging. Now will check every run.

**Comment by Prusias-kol** [comment]
Using tot as well now

**Comment by Prusias-kol** [comment]
Do you break hippy stone in run? Ploop doesn't currently support that due to possibility of things being stolen while you're in leg2->RO->leg1. Thus, ploop only will try to pvp right before you ascend to minimize chance of things getting stolen.

I'll add an optional pref to support the behavior you want though 👍

**Comment by Prusias-kol** [comment]
@capncastom added
