### ISSUE TITLE
Incorrect property name for _mayamSymbolsUsed, for checking whether it was already used when running breakfast.

### ISSUE THREAD

**Issue by Gerhazo** [Prusias-kol/pLooper#12]
The breakfast logic checks whether the property "mayamSymbolsUsed" is empty before using the calendar. However, the actual property name is "_mayamSymbolsUsed", with an underscore.

This causes issues if the user already used the mayam calendar himself before running pLoop, either manually or through kolmafia's breakfast function. The script then fails to use the calendar and stops running.

**Comment by Prusias-kol** [comment]
Fixed thank you!
