### ISSUE TITLE
Add use Can of Rain-doh if pulled from Hagnks

### ISSUE THREAD

**Issue by PharmerGord** [Prusias-kol/pLooper#2]
Suggest that if the player owns the Item of the Month Can of Rain-doh add a line to use the can of rain-doh after pulling all from hagnks. I would suggest adding a this around line 218. 

if ($item [Can of Rain-doh] == true) {
	cli_execute ("use can of rain-doh")} 
I am not sure if that is the full way of adding the option

**Comment by Prusias-kol** [comment]
added
