### ISSUE TITLE
Error running ploop:

### ISSUE THREAD

**Issue by PsychonautJordan** [Prusias-kol/pLooper#9]
> ploop fullday

Unknown variable 'To' (ploop.ash, line 1, char 1 to char 3)
Expected ;, found check (ploop.ash, line 1, char 4 to char 9)
Unknown variable 'check' (ploop.ash, line 1, char 4 to char 9)
Expected ;, found : (ploop.ash, line 1, char 9 to char 10)
Empty or unknown node (ploop.ash, line 1, char 9 to char 10)
Unknown variable 'Make' (ploop.ash, line 1, char 11 to char 15)
Expected ;, found sure (ploop.ash, line 1, char 16 to char 20)
Unknown variable 'sure' (ploop.ash, line 1, char 16 to char 20)
Expected ;, found changing (ploop.ash, line 1, char 21 to char 29)
Unknown variable 'changing' (ploop.ash, line 1, char 21 to char 29)
Expected ;, found item (ploop.ash, line 1, char 30 to char 34)
Expected ;, found doesn (ploop.ash, line 1, char 41 to char 46)
Unknown variable 'doesn' (ploop.ash, line 1, char 41 to char 46)
Expected ;, found ' (ploop.ash, line 1, char 46 to char 47)
No closing ' found (ploop.ash, line 1, char 46 to char 131)
Expected ;, found Make (ploop.ash, line 2, char 1 to char 5)
Unknown variable 'Make' (ploop.ash, line 2, char 1 to char 5)
Expected ;, found sure (ploop.ash, line 2, char 6 to char 10)
Unknown variable 'sure' (ploop.ash, line 2, char 6 to char 10)
Expected ;, found no (ploop.ash, line 2, char 11 to char 13)
Unknown variable 'no' (ploop.ash, line 2, char 11 to char 13)
Expected ;, found items (ploop.ash, line 2, char 14 to char 19)
Unknown variable 'items' (ploop.ash, line 2, char 14 to char 19)
Expected ;, found are (ploop.ash, line 2, char 20 to char 23)
Unknown variable 'are' (ploop.ash, line 2, char 20 to char 23)
Expected ;, found only (ploop.ash, line 2, char 24 to char 28)
Unknown variable 'only' (ploop.ash, line 2, char 24 to char 28)
Expected ;, found slight (ploop.ash, line 2, char 29 to char 35)
Unknown variable 'slight' (ploop.ash, line 2, char 29 to char 35)
Expected ;, found variations (ploop.ash, line 2, char 36 to char 46)
Unknown variable 'variations' (ploop.ash, line 2, char 36 to char 46)
Expected ;, found of (ploop.ash, line 2, char 47 to char 49)
Unknown variable 'of' (ploop.ash, line 2, char 47 to char 49)
Expected ;, found others (ploop.ash, line 2, char 50 to char 56)
Unknown variable 'others' (ploop.ash, line 2, char 50 to char 56)
Invalid field name 'Make' (ploop.ash, line 3, char 1 to char 5)
Expected ;, found sure (ploop.ash, line 3, char 6 to char 10)
Unknown variable 'sure' (ploop.ash, line 3, char 6 to char 10)
Expected ;, found art (ploop.ash, line 3, char 11 to char 14)
Unknown variable 'art' (ploop.ash, line 3, char 11 to char 14)
Expected ;, found specs (ploop.ash, line 3, char 15 to char 20)
Unknown variable 'specs' (ploop.ash, line 3, char 15 to char 20)
Expected ;, found are (ploop.ash, line 3, char 21 to char 24)
Unknown variable 'are' (ploop.ash, line 3, char 21 to char 24)
Expected ;, found good (ploop.ash, line 3, char 25 to char 29)
Unknown variable 'good' (ploop.ash, line 3, char 25 to char 29)
Expected ;, found Make (ploop.ash, line 4, char 1 to char 5)
Unknown variable 'Make' (ploop.ash, line 4, char 1 to char 5)
Expected ;, found sure (ploop.ash, line 4, char 6 to char 10)
Unknown variable 'sure' (ploop.ash, line 4, char 6 to char 10)
Expected ;, found pickup (ploop.ash, line 4, char 11 to char 17)
Unknown variable 'pickup' (ploop.ash, line 4, char 11 to char 17)
Expected ;, found is (ploop.ash, line 4, char 18 to char 20)
Unknown variable 'is' (ploop.ash, line 4, char 18 to char 20)
Expected ;, found sourced (ploop.ash, line 4, char 21 to char 28)
Unknown variable 'sourced' (ploop.ash, line 4, char 21 to char 28)
Expected ;, found Make (ploop.ash, line 5, char 1 to char 5)
Unknown variable 'Make' (ploop.ash, line 5, char 1 to char 5)
Expected ;, found sure (ploop.ash, line 5, char 6 to char 10)
Unknown variable 'sure' (ploop.ash, line 5, char 6 to char 10)
Expected ;, found item (ploop.ash, line 5, char 11 to char 15)
Variable types is already defined (ploop.ash, line 5, char 16 to char 21)
Expected ;, found are (ploop.ash, line 5, char 22 to char 25)
Unknown variable 'are' (ploop.ash, line 5, char 22 to char 25)
Expected ;, found listed (ploop.ash, line 5, char 26 to char 32)
Unknown variable 'listed' (ploop.ash, line 5, char 26 to char 32)
Expected ;, found correctly (ploop.ash, line 5, char 33 to char 42)
Unknown variable 'correctly' (ploop.ash, line 5, char 33 to char 42)
Expected ;, found Make (ploop.ash, line 6, char 1 to char 5)
Unknown variable 'Make' (ploop.ash, line 6, char 1 to char 5)
Expected ;, found sure (ploop.ash, line 6, char 6 to char 10)
Unknown variable 'sure' (ploop.ash, line 6, char 6 to char 10)
Expected ;, found art (ploop.ash, line 6, char 11 to char 14)
Unknown variable 'art' (ploop.ash, line 6, char 11 to char 14)
Expected ;, found is (ploop.ash, line 6, char 15 to char 17)
Unknown variable 'is' (ploop.ash, line 6, char 15 to char 17)
Expected ;, found in (ploop.ash, line 6, char 18 to char 20)
Unknown variable 'in' (ploop.ash, line 6, char 18 to char 20)
Expected ;, found distractors (ploop.ash, line 6, char 21 to char 32)
Unknown variable 'distractors' (ploop.ash, line 6, char 21 to char 32)
Expected ;, found when (ploop.ash, line 6, char 33 to char 37)
Unknown variable 'when' (ploop.ash, line 6, char 33 to char 37)
Expected ;, found appropriate (ploop.ash, line 6, char 38 to char 49)
Expected ), found 541_practice_3 (ploop.ash, line 6, char 51 to char 65)
Function 'appropriate( )' undefined. This script may require a more recent version of KoLmafia and/or its supporting scripts. (ploop.ash, line 6, char 38 to char 49)
Expected ;, found 541_practice_3 (ploop.ash, line 6, char 51 to char 65)
Empty or unknown node (ploop.ash, line 6, char 51 to char 65)
Empty or unknown node (ploop.ash, line 6, char 65 to char 66)
Unknown variable 'Change' (ploop.ash, line 7, char 1 to char 7)
Expected ;, found item (ploop.ash, line 7, char 8 to char 12)
Type given but not used to declare anything (ploop.ash, line 7, char 8 to char 14)
Empty or unknown node (ploop.ash, line 7, char 13 to char 14)
Empty or unknown node (ploop.ash, line 7, char 14 to char 15)
Unknown variable 'change' (ploop.ash, line 7, char 16 to char 22)
Expected ;, found ticket (ploop.ash, line 7, char 23 to char 29)
Unknown variable 'ticket' (ploop.ash, line 7, char 23 to char 29)

**Comment by Prusias-kol** [comment]
fixed
